/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1;

public class App {

  // Method to return a greeting message
  public String getGreeting() {
    return "Hello World!";
  }

  // Corrected Main method for testing
  public static void main(String[] args) {
    App app = new App(); // Create an instance of App
    System.out.println(app.getGreeting()); // Call getGreeting() method
  }

}
